export const GET_FROM_LIKE_LOADING = "GET_FROM_LIKE_LOADING";

export const GET_FROM_LIKE_SUCCESS = "GET_FROM_LIKE_SUCCESS";

export const GET_FROM_LIKE_ERROR = "GET_FROM_LIKE_ERROR";

export const ADD_TO_LIKE_LOADING = "ADD_TO_LIKE_LOADING";

export const ADD_TO_LIKE_SUCCESS = "ADD_TO_LIKE_SUCCESS";

export const ADD_TO_LIKE_ERROR = "ADD_TO_LIKE_ERROR";

export const REMOVE_FROM_LIKE_LOADING = "REMOVE_FROM_LIKE_LOADING";

export const REMOVE_FROM_LIKE_SUCCESS = "REMOVE_FROM_LIKE_SUCCESS";

export const REMOVE_FROM_LIKE_ERROR = "REMOVE_FROM_LIKE_ERROR";
