/*actiontypes*/
export const POST_DATA_TO_CART_LOADING = "POST_DATA_TO_CART_LOADING";

export const POST_DATA_TO_CARTS_SUCCESS = "POST_DATA_TO_CARTS_SUCCESS";

export const POST_DATA_TO_CART_ERROR = "POST_DATA_TO_CART_ERROR";

export const GET_DATA_FOR_CART_LOADING = "GET_DATA_FOR_CART_LOADING";

export const GET_DATA_FOR_CART_SUCCESS = "GET_DATA_FOR_CART_SUCCESS";

export const GET_DATA_FOR_CART_ERROR = "GET_DATA_FOR_CART_ERROR";

export const DELETE_DATA_FROM_CART_LOADING = "DELETE_DATA_FROM_CART_LOADING";

export const DELETE_DATA_FROM_CART_SUCCESS = "DELETE_DATA_FROM_CART_SUCCESS";

export const DELETE_DATA_FROM_CART_ERROR = "DELETE_DATA_FROM_CART_ERROR";